import type { NextPage } from 'next';
import Head from 'next/head';

export const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>kwallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello World</h1>
      </main>
    </>
  );
};
